
<!-- ELECTRONICS -->

<div class="row">
<div class="four columns">
<h3 style="margin-bottom: 0;"><a href="{{store direct_url="electronics/cell-phones.html"}}"><img style="display: block; border: 0;" src="{{skin url='images/media/head_electronics_cellphones.gif}}" alt="Cell Phones" /></a></h3>
<p><a href="{{store direct_url="electronics/cell-phones.html"}}"><img src="{{skin url='images/media/electronics_cellphones.jpg}}" alt="" /></a></p>
</div>
<div class="four columns">
<h3 style="margin-bottom: 0;"><a href="{{store direct_url="electronics/cameras/digital-cameras.html"}}"><img style="display: block; border: 0;" src="{{skin url='images/media/head_electronics_digicamera.gif}}" alt="Digital Cameras" /></a></h3>
<p><a href="{{store direct_url="electronics/cameras/digital-cameras.html"}}"><img src="{{skin url='images/media/electronics_digitalcameras.jpg}}" alt="" /></a></p>
</div>
<div class="four columns">
<h3 style="margin-bottom: 0;"><a href="{{store direct_url="electronics/computers/laptops.html"}}"><img style="display: block; border: 0;" src="{{skin url='images/media/head_electronics_laptops.gif}}" alt="Laptops" /></a></h3>
<p><a href="{{store direct_url="electronics/computers/laptops.html"}}"><img src="{{skin url='images/media/electronics_laptops.jpg}}" alt="" /></a></p>
</div>
</div>