
<!-- HOMEPAGE CONTENT -->

<div class="nine columns best-selling">
<p class="home-callout"><img src="{{skin url='images/home_main_callout.jpg'}}" alt="" border="0" /></p>
<p class="home-callout"><img src="{{skin url='images/free_shipping_callout.jpg'}}" alt="" border="0" /></p>
<h3>Best Selling Products</h3>
<ul>
<li><a href="{{store direct_url="sony-vaio-vgn-txn27n-b-11-1-notebook-pc.html"}}"><img class="product-img" src="{{skin url='images/media/best_selling_img01.jpg'}}" alt="" border="0" /></a>
<div class="product-description">
<p><a href="{{store direct_url="sony-vaio-vgn-txn27n-b-11-1-notebook-pc.html"}}">Sony VAIO VGN-TXN27N/B 11.1" Notebook PC</a></p>
<p>See all <a href="{{store direct_url="electronics/computers/laptops.html"}}">Laptops</a></p>
</div>
</li>
<li><a href="{{store direct_url="nine-west-women-s-lucero-pump.html"}}"><img class="product-img" src="{{skin url='images/media/best_selling_img02.jpg'}}" alt="" border="0" /></a>
<div class="product-description">
<p><a href="{{store direct_url="nine-west-women-s-lucero-pump.html"}}">Nine West Women's Lucero Pump</a></p>
<p>See all <a href="{{store direct_url="apparel/shoes.html"}}">Shoes</a></p>
</div>
</li>
</ul>
<ul>
<li><a href="{{store direct_url="olympus-stylus-750-7-1mp-digital-camera.html"}}"><img class="product-img" src="{{skin url='images/media/best_selling_img03.jpg'}}" alt="" border="0" /></a>
<div class="product-description">
<p><a href="{{store direct_url="olympus-stylus-750-7-1mp-digital-camera.html"}}">Olympus Stylus 750 7.1MP Digital Camera</a></p>
<p>See all <a href="{{store direct_url="electronics/cameras/digital-cameras.html"}}">Digital Cameras</a></p>
</div>
</li>
<li><a href="{{store direct_url="acer-ferrari-3200-notebook-computer-pc.html"}}"><img class="product-img" src="{{skin url='images/media/best_selling_img04.jpg'}}" alt="" border="0" /></a>
<div class="product-description">
<p><a href="{{store direct_url="acer-ferrari-3200-notebook-computer-pc.html"}}">Acer Ferrari 3200 Notebook Computer PC</a></p>
<p>See all <a href="{{store direct_url="electronics/computers/laptops.html"}}">Laptops</a></p>
</div>
</li>
</ul>
<ul>
<li><a href="{{store direct_url="asics-men-s-gel-kayano-xii.html"}}"><img class="product-img" src="{{skin url='images/media/best_selling_img05.jpg'}}" alt="" border="0" /></a>
<div class="product-description">
<p><a href="{{store direct_url="asics-men-s-gel-kayano-xii.html"}}">ASICS&reg; Men's GEL-Kayano&reg; XII</a></p>
<p>See all <a href="{{store direct_url="apparel/shoes.html"}}">Shoes</a></p>
</div>
</li>
<li><a href="{{store direct_url="coalesce-functioning-on-impatience-t-shirt.html"}}"><img class="product-img" src="{{skin url='images/media/best_selling_img06.jpg'}}" alt="" border="0" /></a>
<div class="product-description">
<p><a href="{{store direct_url="coalesce-functioning-on-impatience-t-shirt.html"}}">Coalesce: Functioning On Impatience T-Shirt</a></p>
<p>See all <a href="{{store direct_url="apparel/shirts.html"}}">Shirts</a></p>
</div>
</li>
</ul>
</div>
<div class="three columns col-left side-col">
<p class="home-callout"><a href="{{store direct_url="apparel/shoes/womens/anashria-womens-premier-leather-sandal.html"}}"><img src="{{skin url='images/ph_callout_left_top.gif'}}" alt="" border="0" /></a></p>
<p class="home-callout"><img src="{{skin url='images/ph_callout_left_rebel.jpg'}}" alt="" border="0" /></p>
{{block type="tag/popular" template="tag/popular.phtml"}}</div>